"""Static architecture checks for deny-by-default dependency boundaries."""

from .descriptors import (
    ADMINISTRATIVE_STEP_UP_DESCRIPTOR_PATH,
    DescriptorSourceViolation,
    DescriptorViolationCode,
    analyze_administrative_step_up_descriptor_source,
    scan_administrative_step_up_descriptor_source,
)

from .imports import (
    REPORTER_GATEWAY_IMPORT_POLICY,
    REPORTER_ROOT_URL_IMPORT_POLICY,
    ArchitectureImportViolation,
    ImportPolicy,
    ImportViolationCode,
    analyze_python_source,
    scan_python_file,
    scan_python_package,
)
from .migrations import (
    EXPECTED_LIFECYCLE_MIGRATION_FIELDS,
    MigrationViolation,
    MigrationViolationCode,
    analyze_lifecycle_migration_source,
    scan_lifecycle_migrations,
)
from .orchestration import (
    AUDIT_RETENTION_SOURCE_POLICY,
    CLEANUP_SOURCE_POLICY,
    DELETION_SOURCE_POLICY,
    FINALIZATION_SOURCE_POLICY,
    METADATA_RETENTION_SOURCE_POLICY,
    ORCHESTRATION_SOURCE_POLICIES,
    RETENTION_SOURCE_POLICY,
    OrchestrationSourcePolicy,
    OrchestrationSourceViolation,
    OrchestrationViolationCode,
    analyze_inert_orchestration_source,
    scan_inert_orchestration_sources,
)
from .surfaces import (
    EXPECTED_SETTINGS,
    SurfaceViolation,
    SurfaceViolationCode,
    analyze_css_source,
    analyze_settings_source,
    analyze_template_source,
    analyze_urlconf_source,
    scan_surface_file,
)

__all__ = [
    "ADMINISTRATIVE_STEP_UP_DESCRIPTOR_PATH",
    "DescriptorSourceViolation",
    "DescriptorViolationCode",
    "analyze_administrative_step_up_descriptor_source",
    "scan_administrative_step_up_descriptor_source",
    "REPORTER_GATEWAY_IMPORT_POLICY",
    "REPORTER_ROOT_URL_IMPORT_POLICY",
    "ArchitectureImportViolation",
    "ImportPolicy",
    "ImportViolationCode",
    "analyze_python_source",
    "scan_python_file",
    "scan_python_package",
    "EXPECTED_LIFECYCLE_MIGRATION_FIELDS",
    "MigrationViolation",
    "MigrationViolationCode",
    "analyze_lifecycle_migration_source",
    "scan_lifecycle_migrations",
    "AUDIT_RETENTION_SOURCE_POLICY",
    "CLEANUP_SOURCE_POLICY",
    "DELETION_SOURCE_POLICY",
    "FINALIZATION_SOURCE_POLICY",
    "METADATA_RETENTION_SOURCE_POLICY",
    "ORCHESTRATION_SOURCE_POLICIES",
    "RETENTION_SOURCE_POLICY",
    "OrchestrationSourcePolicy",
    "OrchestrationSourceViolation",
    "OrchestrationViolationCode",
    "analyze_inert_orchestration_source",
    "scan_inert_orchestration_sources",
    "EXPECTED_SETTINGS",
    "SurfaceViolation",
    "SurfaceViolationCode",
    "analyze_css_source",
    "analyze_settings_source",
    "analyze_template_source",
    "analyze_urlconf_source",
    "scan_surface_file",
]
