"""Static architecture checks for deny-by-default dependency boundaries."""

from .imports import (
    REPORTER_GATEWAY_IMPORT_POLICY,
    REPORTER_ROOT_URL_IMPORT_POLICY,
    ArchitectureImportViolation,
    ImportPolicy,
    ImportViolationCode,
    analyze_python_source,
    scan_python_file,
    scan_python_package,
)
from .migrations import (
    EXPECTED_LIFECYCLE_MIGRATION_FIELDS,
    MigrationViolation,
    MigrationViolationCode,
    analyze_lifecycle_migration_source,
    scan_lifecycle_migrations,
)
from .orchestration import (
    DELETION_SOURCE_POLICY,
    FINALIZATION_SOURCE_POLICY,
    ORCHESTRATION_SOURCE_POLICIES,
    OrchestrationSourcePolicy,
    OrchestrationSourceViolation,
    OrchestrationViolationCode,
    analyze_inert_orchestration_source,
    scan_inert_orchestration_sources,
)
from .surfaces import (
    EXPECTED_SETTINGS,
    SurfaceViolation,
    SurfaceViolationCode,
    analyze_css_source,
    analyze_settings_source,
    analyze_template_source,
    analyze_urlconf_source,
    scan_surface_file,
)

__all__ = [
    "REPORTER_GATEWAY_IMPORT_POLICY",
    "REPORTER_ROOT_URL_IMPORT_POLICY",
    "ArchitectureImportViolation",
    "ImportPolicy",
    "ImportViolationCode",
    "analyze_python_source",
    "scan_python_file",
    "scan_python_package",
    "EXPECTED_LIFECYCLE_MIGRATION_FIELDS",
    "MigrationViolation",
    "MigrationViolationCode",
    "analyze_lifecycle_migration_source",
    "scan_lifecycle_migrations",
    "DELETION_SOURCE_POLICY",
    "FINALIZATION_SOURCE_POLICY",
    "ORCHESTRATION_SOURCE_POLICIES",
    "OrchestrationSourcePolicy",
    "OrchestrationSourceViolation",
    "OrchestrationViolationCode",
    "analyze_inert_orchestration_source",
    "scan_inert_orchestration_sources",
    "EXPECTED_SETTINGS",
    "SurfaceViolation",
    "SurfaceViolationCode",
    "analyze_css_source",
    "analyze_settings_source",
    "analyze_template_source",
    "analyze_urlconf_source",
    "scan_surface_file",
]
